// Package pathfinderfixtures replays distance fields generated by a
// corrected C build of libtcod's pathfinder.c against the Go port.
//
// See README.md in this directory for the four upstream defects that make a
// stock build unusable as a reference.
package pathfinderfixtures

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/shindakun/golibtcod/path"
)

type scanner struct{ sc *bufio.Scanner }

func (s *scanner) ints() []int {
	if !s.sc.Scan() {
		return nil
	}
	fields := strings.Fields(s.sc.Text())
	out := make([]int, 0, len(fields))
	for _, f := range fields {
		v, err := strconv.Atoi(f)
		if err != nil {
			return nil
		}
		out = append(out, v)
	}
	return out
}

func TestPathfinderAgainstC(t *testing.T) {
	cf, err := os.Open("corpus.txt")
	if err != nil {
		t.Fatalf("open corpus: %v", err)
	}
	defer cf.Close()
	in := &scanner{sc: bufio.NewScanner(cf)}
	in.sc.Buffer(make([]byte, 1<<22), 1<<22)

	golden, err := os.ReadFile("fixtures_pathfinder.txt")
	if err != nil {
		t.Fatalf("open fixtures: %v", err)
	}
	gold := bufio.NewScanner(strings.NewReader(string(golden)))
	gold.Buffer(make([]byte, 1<<22), 1<<22)

	hdr := in.ints()
	if len(hdr) == 0 {
		t.Fatal("empty corpus")
	}
	n := hdr[0]

	for tc := 0; tc < n; tc++ {
		spec := in.ints()
		if len(spec) < 5 {
			t.Fatalf("case %d: bad header", tc)
		}
		w, h, card, diag, nroots := spec[0], spec[1], spec[2], spec[3], spec[4]

		gi := in.ints()
		cost := make([]int32, len(gi))
		for i, v := range gi {
			cost[i] = int32(v)
		}
		p := path.NewPathfinder(w, h, cost, card, diag)
		if p == nil {
			t.Fatalf("case %d: NewPathfinder returned nil", tc)
		}
		for r := 0; r < nroots; r++ {
			rp := in.ints()
			p.AddRoot(rp[0], rp[1])
		}
		p.Compute()

		// Golden blocks start with a "#N" line.
		if !gold.Scan() {
			t.Fatalf("case %d: fixture ended early", tc)
		}
		if got, want := strings.TrimSpace(gold.Text()), fmt.Sprintf("#%d", tc); got != want {
			t.Fatalf("case %d: fixture desync, got %q want %q", tc, got, want)
		}
		for y := 0; y < h; y++ {
			if !gold.Scan() {
				t.Fatalf("case %d row %d: fixture ended early", tc, y)
			}
			var row strings.Builder
			for x := 0; x < w; x++ {
				if x > 0 {
					row.WriteByte(' ')
				}
				if d := p.Distance(x, y); d == path.PathfinderUnreachable {
					row.WriteString("-1")
				} else {
					fmt.Fprintf(&row, "%d", d)
				}
			}
			if got, want := row.String(), strings.TrimSpace(gold.Text()); got != want {
				t.Errorf("case %d (w=%d h=%d card=%d diag=%d) row %d:\ngot  %s\nwant %s",
					tc, w, h, card, diag, y, got, want)
				break
			}
		}
	}
	t.Logf("verified %d distance fields against corrected C", n)
}
