// Package tilesetfixtures replays golden tileset output generated by the
// real libtcod C code against the Go port.
//
// See gen_tileset.c.txt for the generator and README.md in the parent
// directory for the provenance and tolerance policy.
package tilesetfixtures

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"

	"golibtcod/tileset"
)

// parseFixture reads the C dump: a "cell W H" line, then "cp N" blocks each
// followed by TileHeight rows of '0'/'1' coverage.
func parseFixture(t *testing.T, path string) (w, h int, tiles map[int][]string) {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	tiles = map[int][]string{}
	sc := bufio.NewScanner(f)
	cur := -1
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		switch {
		case line == "" || strings.HasPrefix(line, "== "):
			// header
		case strings.HasPrefix(line, "cell "):
			fmt.Sscanf(line, "cell %d %d", &w, &h)
		case strings.HasPrefix(line, "cp "):
			fields := strings.Fields(line)
			n, err := strconv.Atoi(fields[1])
			if err != nil {
				t.Fatalf("bad codepoint line %q", line)
			}
			if len(fields) > 2 && fields[2] == "MISSING" {
				cur = -1
				continue
			}
			cur = n
			tiles[cur] = nil
		default:
			if cur >= 0 {
				tiles[cur] = append(tiles[cur], line)
			}
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	return w, h, tiles
}

// The Go port must reproduce the C loader's cell size and every glyph
// bitmap exactly. 4x6.bdf is a public-domain font from the ucs-fonts
// collection, vendored here so the comparison stays runnable.
func TestBDFAgainstC(t *testing.T) {
	const font = "4x6.bdf"
	wantW, wantH, wantTiles := parseFixture(t, "fixtures_tileset_4x6.txt")

	ts, err := tileset.LoadBDF(font)
	if err != nil {
		t.Fatalf("LoadBDF: %v", err)
	}
	if ts.TileWidth != wantW || ts.TileHeight != wantH {
		t.Fatalf("cell size = %dx%d, C had %dx%d", ts.TileWidth, ts.TileHeight, wantW, wantH)
	}

	checked := 0
	for cp, wantRows := range wantTiles {
		cov := ts.Coverage(cp)
		if cov == nil {
			t.Errorf("codepoint %d: no tile, C had one", cp)
			continue
		}
		if len(wantRows) != ts.TileHeight {
			t.Fatalf("codepoint %d: fixture has %d rows, cell is %d tall", cp, len(wantRows), ts.TileHeight)
		}
		for y, row := range wantRows {
			for x := 0; x < ts.TileWidth; x++ {
				got := byte('0')
				if cov[y*ts.TileWidth+x] >= 128 {
					got = '1'
				}
				if x >= len(row) {
					t.Fatalf("codepoint %d row %d: fixture row %q too short", cp, y, row)
				}
				if got != row[x] {
					t.Errorf("codepoint %d pixel (%d,%d): got %c want %c\ngot row:  %s\nwant row: %s",
						cp, x, y, got, row[x], coverageRow(cov, ts.TileWidth, y), row)
					break
				}
			}
		}
		checked++
	}
	if checked == 0 {
		t.Fatal("no codepoints checked; fixture parse likely failed")
	}
	t.Logf("verified %d glyph bitmaps (%dx%d cells) against C", checked, wantW, wantH)
}

func coverageRow(cov []uint8, w, y int) string {
	var b strings.Builder
	for x := 0; x < w; x++ {
		if cov[y*w+x] >= 128 {
			b.WriteByte('1')
		} else {
			b.WriteByte('0')
		}
	}
	return b.String()
}

// The font declares 919 encoded glyphs; the loader must find them all.
func TestBDFGlyphCount(t *testing.T) {
	ts, err := tileset.LoadBDF("4x6.bdf")
	if err != nil {
		t.Fatal(err)
	}
	if got := len(ts.Codepoints()); got != 919 {
		t.Errorf("loaded %d codepoints, want 919", got)
	}
}
