// Package wrapfixtures replays word-wrapped console output generated by the
// real libtcod C code against the Go port.
//
// See gen_wrap.c.txt for the generator and README.md in the parent directory
// for provenance. corpus.txt is one case per line, tab separated:
// width, height, alignment, text (with \n as a literal escape).
package wrapfixtures

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/shindakun/golibtcod/console"
)

func render(w, h, align int, text string) string {
	c := console.New(w, h)
	c.Clear()
	rh := c.PrintRect(0, 0, w, h, text, nil, nil, console.Alignment(align), console.BkgndNone)
	var b strings.Builder
	fmt.Fprintf(&b, "h=%d\n", rh)
	for y := 0; y < c.H; y++ {
		b.WriteByte('|')
		for x := 0; x < c.W; x++ {
			ch := c.Char(x, y)
			if ch == 0 || ch == ' ' {
				b.WriteByte(' ')
			} else {
				b.WriteRune(rune(ch))
			}
		}
		b.WriteString("|\n")
	}
	return b.String()
}

// Every case in the corpus must render exactly as the C implementation did,
// glyph for glyph, including the reported height.
func TestWrapAgainstC(t *testing.T) {
	corpus, err := os.Open("corpus.txt")
	if err != nil {
		t.Fatalf("open corpus: %v", err)
	}
	defer corpus.Close()

	golden, err := os.ReadFile("fixtures_wrap.txt")
	if err != nil {
		t.Fatalf("open fixtures: %v", err)
	}
	// The C dump is "#N h=..\n" then one bordered row per console line.
	blocks := strings.Split(string(golden), "#")

	sc := bufio.NewScanner(corpus)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	idx := 0
	for sc.Scan() {
		parts := strings.SplitN(sc.Text(), "\t", 4)
		if len(parts) < 4 {
			continue
		}
		w, _ := strconv.Atoi(parts[0])
		h, _ := strconv.Atoi(parts[1])
		a, _ := strconv.Atoi(parts[2])
		text := strings.ReplaceAll(parts[3], `\n`, "\n")

		if idx+1 >= len(blocks) {
			t.Fatalf("case %d: fixture is short", idx)
		}
		// Strip the leading "N " from the block header.
		want := blocks[idx+1]
		if sp := strings.IndexByte(want, ' '); sp >= 0 {
			want = want[sp+1:]
		}
		got := render(w, h, a, text)
		if got != want {
			t.Errorf("case %d (w=%d h=%d align=%d text=%q):\ngot:\n%swant:\n%s",
				idx, w, h, a, text, got, want)
			if testing.Short() {
				return
			}
		}
		idx++
	}
	if idx == 0 {
		t.Fatal("no cases replayed")
	}
	t.Logf("verified %d wrapped layouts against C", idx)
}
