// Package fixtures replays golden fixtures generated by gen.c (compiled
// against the actual libtcod C sources; see gen.c in this directory)
// and asserts the Go port reproduces them. Integer/grid fixtures must be
// exact; float fixtures allow 1e-5 relative tolerance for compiler
// reassociation, with most values expected bit-identical.
package fixtures

import (
	_ "embed"
	"fmt"
	"math"
	"strconv"
	"strings"
	"testing"

	"github.com/shindakun/golibtcod/bresenham"
	"github.com/shindakun/golibtcod/bsp"
	"github.com/shindakun/golibtcod/fov"
	"github.com/shindakun/golibtcod/heightmap"
	"github.com/shindakun/golibtcod/noise"
	"github.com/shindakun/golibtcod/path"
	"github.com/shindakun/golibtcod/rng"
)

//go:embed fixtures.txt
var fixturesRaw string

type section struct {
	header string // full "== ..." line without the marker
	lines  []string
}

func parseSections(t *testing.T) []section {
	t.Helper()
	var secs []section
	for _, line := range strings.Split(fixturesRaw, "\n") {
		if strings.HasPrefix(line, "== ") {
			secs = append(secs, section{header: strings.TrimPrefix(line, "== ")})
		} else if line != "" && len(secs) > 0 {
			secs[len(secs)-1].lines = append(secs[len(secs)-1].lines, line)
		}
	}
	if len(secs) == 0 {
		t.Fatal("no fixture sections parsed")
	}
	return secs
}

func atoi(t *testing.T, s string) int {
	t.Helper()
	v, err := strconv.Atoi(s)
	if err != nil {
		t.Fatalf("bad int %q: %v", s, err)
	}
	return v
}

func atof(t *testing.T, s string) float32 {
	t.Helper()
	v, err := strconv.ParseFloat(s, 32)
	if err != nil {
		t.Fatalf("bad float %q: %v", s, err)
	}
	return float32(v)
}

func closeEnough(a, b float32) bool {
	if a == b {
		return true
	}
	diff := math.Abs(float64(a - b))
	if diff <= 1e-6 { // absolute floor for near-zero values (ULP noise)
		return true
	}
	scale := math.Max(math.Abs(float64(a)), math.Abs(float64(b)))
	return diff <= 1e-5*scale
}

/* --- the same maps gen.c uses --- */

var fovMap1 = []string{
	"................",
	"....##......#...",
	"....##...#......",
	".........#......",
	"..####..........",
	"..#..#....###...",
	"..#..#....#.#...",
	"..#.......###...",
	"..####..........",
	".......#........",
	".......#........",
	"................",
}

var fovMap2 = []string{
	"##########",
	"#........#",
	"#..#..#..#",
	"#........#",
	"#..#..#..#",
	"#........#",
	"##########",
}

var pathMap = []string{
	"####################",
	"#........#.........#",
	"#........#.........#",
	"#...##...#....#....#",
	"#...##...#....#....#",
	"#...##........#....#",
	"#...#####..####....#",
	"#..................#",
	"####################",
}

func buildFovMap(rows []string) *fov.Map {
	m := fov.NewMap(len(rows[0]), len(rows))
	for y, row := range rows {
		for x, ch := range row {
			m.SetProperties(x, y, ch != '#', ch != '#')
		}
	}
	return m
}

var fovAlgoByName = map[string]fov.Algorithm{
	"BASIC": fov.Basic, "DIAMOND": fov.Diamond, "SHADOW": fov.Shadow,
	"PERM0": fov.Permissive0, "PERM4": fov.Permissive4, "PERM8": fov.Permissive8,
	"RESTRICTIVE": fov.Restrictive, "SYMMETRIC": fov.SymmetricShadowcast,
}

/* --- rng replay: one generator per (algo,seed), sections consumed in file order --- */

func TestRngFixtures(t *testing.T) {
	gens := map[string]*rng.Random{}
	getGen := func(algoName string, seed uint32) *rng.Random {
		key := fmt.Sprintf("%s-%d", algoName, seed)
		if g, ok := gens[key]; ok {
			return g
		}
		algo := rng.MT
		if algoName == "CMWC" {
			algo = rng.CMWC
		}
		g := rng.New(algo, seed)
		gens[key] = g
		return g
	}
	n := 0
	for _, sec := range parseSections(t) {
		f := strings.Fields(sec.header)
		if !strings.HasPrefix(f[0], "rng_") {
			continue
		}
		seed64, _ := strconv.ParseUint(f[2], 10, 32)
		g := getGen(f[1], uint32(seed64))
		for i, line := range sec.lines {
			switch f[0] {
			case "rng_u32":
				want := atoi(t, line)
				if got := g.GetI(0, 2147483646); got != want {
					t.Fatalf("%s[%d]: got %d want %d", sec.header, i, got, want)
				}
			case "rng_f":
				want := atof(t, line)
				if got := g.GetF(0, 1); got != want {
					t.Fatalf("%s[%d]: got %v want %v", sec.header, i, got, want)
				}
			case "rng_i_range":
				want := atoi(t, line)
				if got := g.GetI(-17, 1234); got != want {
					t.Fatalf("%s[%d]: got %d want %d", sec.header, i, got, want)
				}
			case "rng_gauss":
				g.SetDistribution(rng.GaussianRange)
				want := atoi(t, line)
				if got := g.GetInt(-50, 50); got != want {
					t.Fatalf("%s[%d]: got %d want %d", sec.header, i, got, want)
				}
			case "rng_gauss_inv":
				g.SetDistribution(rng.GaussianRangeInverse)
				want := atoi(t, line)
				if got := g.GetInt(-50, 50); got != want {
					t.Fatalf("%s[%d]: got %d want %d", sec.header, i, got, want)
				}
			case "rng_dice":
				g.SetDistribution(rng.Linear)
				want := atoi(t, line)
				if got := g.RollS("3d6+2"); got != want {
					t.Fatalf("%s[%d]: got %d want %d", sec.header, i, got, want)
				}
			}
			n++
		}
	}
	t.Logf("verified %d rng values against C", n)
}

func TestBresenhamFixtures(t *testing.T) {
	n := 0
	for _, sec := range parseSections(t) {
		f := strings.Fields(sec.header)
		if f[0] != "bres" {
			continue
		}
		x0, y0 := atoi(t, f[1]), atoi(t, f[2])
		x1, y1 := atoi(t, f[3]), atoi(t, f[4])
		pts := bresenham.Points(x0, y0, x1, y1)
		if len(pts) != len(sec.lines) {
			t.Fatalf("%s: %d points, C had %d", sec.header, len(pts), len(sec.lines))
		}
		for i, line := range sec.lines {
			c := strings.Fields(line)
			if pts[i][0] != atoi(t, c[0]) || pts[i][1] != atoi(t, c[1]) {
				t.Fatalf("%s[%d]: got %v want %s", sec.header, i, pts[i], line)
			}
			n++
		}
	}
	t.Logf("verified %d bresenham cells against C", n)
}

func TestFovFixtures(t *testing.T) {
	cells := 0
	for _, sec := range parseSections(t) {
		f := strings.Fields(sec.header)
		if f[0] != "fov" {
			continue
		}
		rows := fovMap1
		if f[1] == "map2" {
			rows = fovMap2
		}
		m := buildFovMap(rows)
		algo := fovAlgoByName[f[2]]
		px, py := atoi(t, f[3]), atoi(t, f[4])
		radius := atoi(t, f[5])
		lightWalls := f[6] == "1"
		if err := m.ComputeFov(px, py, radius, lightWalls, algo); err != nil {
			t.Fatalf("%s: %v", sec.header, err)
		}
		for y, line := range sec.lines {
			for x, ch := range line {
				want := ch == '1'
				if got := m.InFov(x, y); got != want {
					t.Fatalf("%s: cell (%d,%d) got %v want %v", sec.header, x, y, got, want)
				}
				cells++
			}
		}
	}
	t.Logf("verified %d fov cells against C", cells)
}

func TestPathFixtures(t *testing.T) {
	m := buildFovMap(pathMap)
	costFn := func(xf, yf, xt, yt int) float32 {
		if pathMap[yt][xt] == '#' {
			return 0.0
		}
		if xt >= 10 {
			return 3.0
		}
		return 1.0
	}
	for _, sec := range parseSections(t) {
		f := strings.Fields(sec.header)
		switch f[0] {
		case "astar":
			var p *path.AStar
			if f[1] == "map" {
				dc := atof(t, f[2])
				p = path.NewUsingMap(m, dc)
			} else {
				p = path.NewUsingFunc(20, 9, costFn, 1.41)
			}
			okWant := f[len(f)-1] == "1"
			ok := p.Compute(1, 1, 18, 7)
			if ok != okWant {
				t.Fatalf("%s: compute=%v want %v", sec.header, ok, okWant)
			}
			if p.Size() != len(sec.lines) {
				t.Fatalf("%s: size %d, C had %d", sec.header, p.Size(), len(sec.lines))
			}
			for i, line := range sec.lines {
				c := strings.Fields(line)
				x, y := p.Get(i)
				if x != atoi(t, c[0]) || y != atoi(t, c[1]) {
					t.Fatalf("%s[%d]: got (%d,%d) want %s", sec.header, i, x, y, line)
				}
			}
		case "dijkstra":
			d := path.NewDijkstra(m, 1.41)
			d.Compute(1, 1)
			if f[1] == "dist" {
				for y, line := range sec.lines {
					for x, tok := range strings.Fields(line) {
						want := atof(t, tok)
						got := d.Distance(x, y)
						// C prints %.2f; compare at that precision
						if math.Abs(float64(got-want)) > 0.005 {
							t.Fatalf("dijkstra dist (%d,%d): got %v want %v", x, y, got, want)
						}
					}
				}
			} else { // path
				if !d.PathSet(18, 7) {
					t.Fatal("dijkstra PathSet failed")
				}
				var got [][2]int
				for {
					x, y, ok := d.PathWalk()
					if !ok {
						break
					}
					got = append(got, [2]int{x, y})
				}
				if len(got) != len(sec.lines) {
					t.Fatalf("dijkstra path len %d, C had %d", len(got), len(sec.lines))
				}
				for i, line := range sec.lines {
					c := strings.Fields(line)
					if got[i][0] != atoi(t, c[0]) || got[i][1] != atoi(t, c[1]) {
						t.Fatalf("dijkstra path[%d]: got %v want %s", i, got[i], line)
					}
				}
			}
		}
	}
}

func TestBspFixtures(t *testing.T) {
	for _, sec := range parseSections(t) {
		f := strings.Fields(sec.header)
		if f[0] != "bsp" {
			continue
		}
		seed64, _ := strconv.ParseUint(f[1], 10, 32)
		r := rng.New(rng.CMWC, uint32(seed64))
		root := bsp.New(0, 0, 80, 50)
		root.SplitRecursive(r, 5, 6, 6, 1.5, 1.5)
		var got []string
		root.TraversePreOrder(func(n *bsp.BSP) bool {
			h := 0
			if n.Horizontal {
				h = 1
			}
			got = append(got, fmt.Sprintf("%d %d %d %d %d %d %d", n.X, n.Y, n.W, n.H, n.Level, h, n.Position))
			return true
		})
		if len(got) != len(sec.lines) {
			t.Fatalf("%s: %d nodes, C had %d", sec.header, len(got), len(sec.lines))
		}
		for i := range got {
			if got[i] != sec.lines[i] {
				t.Fatalf("%s node %d:\n got %q\nwant %q", sec.header, i, got[i], sec.lines[i])
			}
		}
	}
}

func TestNoiseFixtures(t *testing.T) {
	var cur *noise.Noise
	exact, near, total := 0, 0, 0
	check := func(header string, i int, got, want float32) {
		total++
		if got == want {
			exact++
			return
		}
		if closeEnough(got, want) {
			near++
			return
		}
		t.Fatalf("%s[%d]: got %v want %v", header, i, got, want)
	}
	for _, sec := range parseSections(t) {
		f := strings.Fields(sec.header)
		switch f[0] {
		case "noise":
			ndim := atoi(t, f[1])
			cur = noise.New(ndim, noise.DefaultHurst, noise.DefaultLacunarity, rng.New(rng.CMWC, 0x5EED))
			for i, line := range sec.lines {
				w := strings.Fields(line)
				fv := []float32{
					float32(i)*0.173 - 2.0, float32(i)*0.117 + 0.5,
					float32(i)*0.071 - 1.0, float32(i) * 0.045,
				}[:4]
				check(sec.header, i, cur.GetEx(fv, noise.Perlin), atof(t, w[0]))
				check(sec.header, i, cur.GetEx(fv, noise.Simplex), atof(t, w[1]))
				check(sec.header, i, cur.GetFbmEx(fv, 4.5, noise.Simplex), atof(t, w[2]))
				check(sec.header, i, cur.GetTurbulenceEx(fv, 3.25, noise.Perlin), atof(t, w[3]))
			}
		case "noise_wavelet":
			for i, line := range sec.lines {
				fv := []float32{float32(i) * 0.211, float32(i) * 0.137, float32(i) * 0.093, 0}
				check(sec.header, i, cur.GetEx(fv, noise.Wavelet), atof(t, line))
			}
		}
	}
	t.Logf("noise: %d/%d bit-exact, %d within tolerance", exact, total, near)
}

func TestHeightmapFixtures(t *testing.T) {
	exact, near, total := 0, 0, 0
	check := func(where string, got, want float32) {
		total++
		if got == want {
			exact++
			return
		}
		if closeEnough(got, want) {
			near++
			return
		}
		t.Fatalf("%s: got %v want %v", where, got, want)
	}
	var chain *heightmap.HeightMap
	for _, sec := range parseSections(t) {
		f := strings.Fields(sec.header)
		if f[0] != "heightmap" {
			continue
		}
		switch f[1] {
		case "chain":
			r := rng.New(rng.CMWC, 0xBEEF)
			nz := noise.New(2, noise.DefaultHurst, noise.DefaultLacunarity, rng.New(rng.CMWC, 0xBEEF))
			hm := heightmap.New(17, 17)
			hm.AddHill(8.0, 8.0, 6.0, 1.0)
			hm.AddHill(3.5, 4.5, 3.0, 0.5)
			hm.DigHill(12.0, 12.0, 4.0, -0.5)
			hm.AddFbm(nz, 3.0, 3.0, 0.0, 0.0, 4.0, 0.0, 0.5)
			hm.RainErosion(200, 0.05, 0.05, r)
			hm.Normalize(0.0, 1.0)
			chain = hm
			for y, line := range sec.lines {
				for x, tok := range strings.Fields(line) {
					check(fmt.Sprintf("chain (%d,%d)", x, y), hm.At(x, y), atof(t, tok))
				}
			}
		case "interp":
			for i, line := range sec.lines {
				got := chain.InterpolatedValue(float32(i)*1.55, float32(i)*1.15)
				check(fmt.Sprintf("interp %d", i), got, atof(t, line))
			}
		case "mpd":
			r := rng.New(rng.MT, 11)
			hm := heightmap.New(33, 33)
			hm.MidPointDisplacement(r, 0.5)
			for y, line := range sec.lines {
				for x, tok := range strings.Fields(line) {
					check(fmt.Sprintf("mpd (%d,%d)", x, y), hm.At(x, y), atof(t, tok))
				}
			}
		}
	}
	t.Logf("heightmap: %d/%d bit-exact, %d within tolerance", exact, total, near)
}
